

all:
	gcc -Wall -c -fPIC basic.c -I/home/adcastel/argobots/include -L/home/adcastel/argobots/lib -labt
	gcc -shared -o libiomp5.so basic.o -I/home/adcastel/argobots/include -L/home/adcastel/argobots/lib -labt

